# Word Vector Visualization

visualization: interesting discoveries

In [1]:
from gensim.models.keyedvectors import KeyedVectors

#### 1. load data

In [2]:
word2vec_bin_file = '/Users/chenwang/Workspace/datasets/GoogleNews-vectors-negative300.bin.gz'

word_vectors = KeyedVectors.load_word2vec_format(word2vec_bin_file, binary=True)

#### 2. check word vectors for a specific word

In [13]:
word_vectors['hello']

array([-0.05419922,  0.01708984, -0.00527954,  0.33203125, -0.25      ,
       -0.01397705, -0.15039062, -0.265625  ,  0.01647949,  0.3828125 ,
       -0.03295898, -0.09716797, -0.16308594, -0.04443359,  0.00946045,
        0.18457031,  0.03637695,  0.16601562,  0.36328125, -0.25585938,
        0.375     ,  0.171875  ,  0.21386719, -0.19921875,  0.13085938,
       -0.07275391, -0.02819824,  0.11621094,  0.15332031,  0.09082031,
        0.06787109, -0.0300293 , -0.16894531, -0.20800781, -0.03710938,
       -0.22753906,  0.26367188,  0.012146  ,  0.18359375,  0.31054688,
       -0.10791016, -0.19140625,  0.21582031,  0.13183594, -0.03515625,
        0.18554688, -0.30859375,  0.04785156, -0.10986328,  0.14355469,
       -0.43554688, -0.0378418 ,  0.10839844,  0.140625  , -0.10595703,
        0.26171875, -0.17089844,  0.39453125,  0.12597656, -0.27734375,
       -0.28125   ,  0.14746094, -0.20996094,  0.02355957,  0.18457031,
        0.00445557, -0.27929688, -0.03637695, -0.29296875,  0.19

In [14]:
word_vectors.__getitem__('hello')

array([-0.05419922,  0.01708984, -0.00527954,  0.33203125, -0.25      ,
       -0.01397705, -0.15039062, -0.265625  ,  0.01647949,  0.3828125 ,
       -0.03295898, -0.09716797, -0.16308594, -0.04443359,  0.00946045,
        0.18457031,  0.03637695,  0.16601562,  0.36328125, -0.25585938,
        0.375     ,  0.171875  ,  0.21386719, -0.19921875,  0.13085938,
       -0.07275391, -0.02819824,  0.11621094,  0.15332031,  0.09082031,
        0.06787109, -0.0300293 , -0.16894531, -0.20800781, -0.03710938,
       -0.22753906,  0.26367188,  0.012146  ,  0.18359375,  0.31054688,
       -0.10791016, -0.19140625,  0.21582031,  0.13183594, -0.03515625,
        0.18554688, -0.30859375,  0.04785156, -0.10986328,  0.14355469,
       -0.43554688, -0.0378418 ,  0.10839844,  0.140625  , -0.10595703,
        0.26171875, -0.17089844,  0.39453125,  0.12597656, -0.27734375,
       -0.28125   ,  0.14746094, -0.20996094,  0.02355957,  0.18457031,
        0.00445557, -0.27929688, -0.03637695, -0.29296875,  0.19

#### 3. vectors of compound words

n-grams 使用下划线连接

In [15]:
word_vectors.__getitem__('Los_Angeles')

array([-1.19140625e-01,  2.65625000e-01, -1.69921875e-01,  1.50390625e-01,
       -6.88476562e-02,  1.45507812e-01, -3.22265625e-01, -7.12890625e-02,
       -1.81884766e-02, -5.29785156e-02, -1.79687500e-01,  2.94921875e-01,
        1.30859375e-01,  9.71679688e-02,  1.33789062e-01, -4.76074219e-02,
       -1.30859375e-01,  1.21093750e-01, -3.16406250e-01,  3.18359375e-01,
       -2.27050781e-02, -4.05273438e-02, -1.98242188e-01, -8.59375000e-02,
       -8.15429688e-02,  1.81640625e-01, -3.90625000e-02,  3.32031250e-02,
       -3.51562500e-01,  1.04980469e-02,  1.21093750e-01, -9.81445312e-02,
       -6.68945312e-02, -6.25000000e-02,  1.75781250e-01,  8.93554688e-02,
        3.19824219e-02, -1.08886719e-01,  4.82177734e-03,  2.77343750e-01,
       -1.04980469e-01, -8.59375000e-02,  4.24804688e-02, -1.35742188e-01,
       -1.36718750e-01,  3.73046875e-01,  8.15429688e-02, -6.39648438e-02,
        2.98828125e-01,  2.27539062e-01,  1.81640625e-01,  7.81250000e-02,
        3.83300781e-02, -

#### 4. 计算距离

In [16]:
import numpy as np

计算两个单词的欧式距离

In [17]:
np.linalg.norm(word_vectors['Illinois'] - word_vectors['Illini'])



3.36538

计算两个节点的cosine 距离

In [19]:
cos_similarity = np.dot(word_vectors['Illinois'], word_vectors['Illini']) / (np.linalg.norm(word_vectors['Illinois']) * np.linalg.norm(word_vectors['Illini']))
cos_similarity



0.5501352

In [20]:
# Cosine distance

1 - cos_similarity

0.44986480474472046

从上面的结果可以看出，这两个词的语义距离差距不大。

## 2. visualization

In [22]:
columns = ['geonameid', 'name', 'asciiname', 'alternatenames', 'latitude', 'longitude', 'feature class',
               'feature code', 'country code']
columns += ['cc2', 'admin1_code', 'admin2_code', 'admin3_code', 'admin4_code', 'population', 'elevation',
                'dem', 'timezone', 'modification date']

columns

['geonameid',
 'name',
 'asciiname',
 'alternatenames',
 'latitude',
 'longitude',
 'feature class',
 'feature code',
 'country code',
 'cc2',
 'admin1_code',
 'admin2_code',
 'admin3_code',
 'admin4_code',
 'population',
 'elevation',
 'dem',
 'timezone',
 'modification date']

In [23]:
columns = [c.lower().replace(' ', '_') for c in columns]

columns

['geonameid',
 'name',
 'asciiname',
 'alternatenames',
 'latitude',
 'longitude',
 'feature_class',
 'feature_code',
 'country_code',
 'cc2',
 'admin1_code',
 'admin2_code',
 'admin3_code',
 'admin4_code',
 'population',
 'elevation',
 'dem',
 'timezone',
 'modification_date']

In [27]:
city1000 = '/Users/chenwang/Workspace/github/natural_language_processing_in_action/datasets/cities1000.txt'
us_state = '/Users/chenwang/Workspace/github/natural_language_processing_in_action/datasets/states.csv'


In [30]:
import pandas as pd

cities = pd.read_csv(city1000, sep='\t', index_col=None, low_memory=False, header=None)
cities.columns = columns

In [32]:
us = cities[(cities.country_code == 'US') & (cities.admin1_code.notnull())].copy()

In [28]:
states = pd.read_csv(us_state)

In [33]:
states = dict(zip(states.Abbreviation, states.State))

In [34]:
us['city'] = us.name.copy()
us['st'] = us.admin1_code.copy()
us['state'] = us.st.map(states)

In [37]:
us[us.columns[-3:]].head()

city  st    state
118528     Bay Minette  AL  Alabama
118529            Edna  TX    Texas
118530  Bayou La Batre  AL  Alabama
118531       Henderson  TX    Texas
118532         Natalia  TX    Texas

现在我们对于每个城市都有对应的state name 和abbr. 

In [38]:
vocab = pd.np.concatenate([us.city, us.st, us.state])
vocab = np.array([word for word in vocab if word in word_vectors])
vocab[:5]

/Users/chenwang/anaconda3/envs/tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.


array(['Edna', 'Henderson', 'Natalia', 'Yorktown', 'Brighton'],
      dtype='<U15')

In [39]:
len(vocab)

41316

In [40]:
city_plus_state = []

In [42]:
for c, state, st in zip(us.city, us.state, us.st):
    if c not in vocab:
        continue
    row = []

    if state in vocab:
        row.extend(word_vectors[c] + word_vectors[state])
    else:
        row.extend(word_vectors[c] + word_vectors[st])
    
    city_plus_state.append(row)

In [43]:
us_300D = pd.DataFrame(city_plus_state)

In [46]:
type(us_300D)

pandas.core.frame.DataFrame

In [50]:
us_300D.shape

(10950, 300)

In [44]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2) 
us_2D = pca.fit_transform(us_300D.iloc[:, :300])

In [49]:
us_2D.shape

(10950, 2)

In [51]:
# 这里需要构建一个2D 的df

#### plot

In [45]:
def offline_plotly_scatter_bubble(df, x='x', y='y', size_col='size', text_col='text',
                                  category_col='category', possible_categories=None,
                                  filename=None,
                                  config={'displaylogo': False},
                                  xscale=None, yscale='log',
                                  layout={'hovermode': 'closest', 'showlegend': False, 'autosize': True},
                                  marker={'sizemode': 'area'},
                                  min_size=10,
                                  ):
    r"""Interactive scatterplot of a DataFrame with the size and color of circles linke to two columns

    config keys:
      fillFrame setBackground displaylogo sendData showLink linkText staticPlot scrollZoom plot3dPixelRatio displayModeBar
      showTips workspace doubleClick autosizable editable

    layout keys:
      angularaxis annotations autosize bargap bargroupgap barmode barnorm boxgap boxgroupgap boxmode calendar
      direction dragmode font geo height hiddenlabels hiddenlabelssrc hidesources hovermode images legend
      mapbox margin orientation paper_bgcolor plot_bgcolor radialaxis scene separators shapes showlegend sliders smith
      ternary title titlefont updatemenus width xaxis yaxis

    marker keys:
      autocolorscale blend border cauto cmax cmin color colorbar colors colorscale colorsrc colorssrc line maxdisplayed
      opacity opacitysrc outliercolor reversescale showscale size sizemax sizemin sizemode sizeref sizesrc symbol symbolsrc

    marker['sizeref'] gives the denominator of the circle scaling factor.
      Typically it should be about a tenth of the minimum 'size' column value

    >>> from nlpia.data.loaders import get_data
    >>> df = get_data('cities_us_wordvectors_pca2_meta').iloc[:100]
    >>> html = offline_plotly_scatter_bubble(
    ...     df.sort_values('population', ascending=False)[:350].copy().sort_values('population'),
    ...     x='x', y='y',
    ...     size_col='population', text_col='name', category_col='timezone',
    ...     xscale=None, yscale=None,  # 'log' or None
    ...     layout={}, marker={'sizeref': 3000})
    """
    config_default = dict(DEFAULT_PLOTLY_CONFIG)
    marker_default = {
        'size': size_col or min_size,
        'sizemode': 'area',
        'sizeref': int(df[size_col].min() * .8) if size_col else min_size}
    marker_default.update(marker)
    size_col = marker_default.pop('size')
    layout_default = {
        'xaxis': XAxis(title=x, type=xscale),
        'yaxis': YAxis(title=y, type=yscale),
    }
    layout_default.update(**layout)
    if config is not None:
        config_default.update(config)
    df.columns = clean_columns(df.columns)
    if possible_categories is None and category_col is not None:
        if category_col in df.columns:
            category_labels = df[category_col]
        else:
            category_labels = np.array(category_col)
        possible_categories = list(set(category_labels))
    possible_categories = [None] if possible_categories is None else possible_categories
    if category_col and category_col in df:
        masks = [np.array(df[category_col] == label) for label in possible_categories]
    else:
        masks = [np.array([True] * len(df))] * len(possible_categories)
    data = {'data': [
            Scatter(x=df[x][mask].values,
                    y=df[y][mask].values,
                    text=df[text_col][mask].values,
                    marker=Marker(size=df[size_col][mask] if size_col in df.columns else size_col,
                                  **marker_default),
                    mode='markers',
                    name=str(category_name)) for (category_name, mask) in zip(possible_categories, masks)
            ],
            'layout': Layout(**layout_default)
            }
    return offline_plotly_data(data, filename=filename, config=config_default)


In [53]:
import seaborn
from matplotlib import pyplot as plt
html = offline_plotly_scatter_bubble(
    us_2D_df.sort_values('population', ascending=False)[:350].copy().sort_values('population'),
    filename='plotly_scatter_bubble.html',
    x='x', y='y',
    size_col='population', text_col='name', category_col='timezone',
    xscale=None, yscale=None, # 'log' or None
    layout={}, marker={'sizeref': 3000})

KeyError: 'population'